name: Create new org

on:
  issue_comment:
    types: [created]

env:
  billing_email: 'test@test.com'
  enterprise_id: 'MDEwOkVudGVycHJpc2Uy'

jobs:
  create-repo:
    name: Create new org
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, '/create-org') &&
      contains(github.event.issue.labels.*.name, 'new-org')

    steps:
      - uses: actions/checkout@v3
      
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: ApproveOps - Approvals in IssueOps
        uses: joshjohanning/approveops@v1
        id: check-approval
        with:
          app-id: 170284 # The GitHub App ID; ie: 170284
          app-private-key: ${{ secrets.PRIVATE_KEY }} # Private key for the GitHub App that is installed on the repo; e.g.: ${{ secrets.PRIVATE_KEY }}
          team-name: approver-team # The name of the team in GitHub to check for the approval command; e.g.: approver-team
          fail-if-approval-not-found: true # Fail the action (show the action run as red) if the command is not found in the comments from someone in the approver team"

      - uses: stefanbuck/github-issue-parser@v2
        id: issue-parser

      - name: do things
        env:
          GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          echo "new org name = ${{ steps.issue-parser.outputs.issueparser_org_name }}"
          echo "org admin = ${{ github.event.issue.user.login }}"
          echo "org billing email = ${{ env.billing_email }}"

          # create the org
          # commented out for now
          # curl -LX POST 'https://api.github.com/graphql' \
          #   -H "Authorization: bearer ${{ secrets.ADMIN_TOKEN }}" \
          #   --data '{ "query": "mutation ($enterprise_id: ID! $organization_name: String! $admin_logins: [String!]! $billing_email: String!) { createEnterpriseOrganization(input: { enterpriseId: $enterprise_id login: $organization_name billingEmail: $billing_email profileName: $organization_name adminLogins: $admin_logins }) { enterprise { name } organization { id name } } }", "variables":{ "enterprise_id": "${{ env.enterprise_id }}", "organization_name": "${{ steps.issue-parser.outputs.issueparser_org_name }}", "billing_email": "${{ env.billing_email }}", "admin_logins": [ "${{ github.event.issue.user.login }}" ] } }'
          
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            /orgs/${{ steps.issue-parser.outputs.issueparser_org_name }} \
            -f default_repository_permission='none' \
            -F members_can_create_repositories=true \
            -f members_allowed_repository_creation_type='private' \
            -F members_can_create_public_repositories=false \
            -F members_can_create_private_repositories=true \
            -F members_can_create_internal_repositories=false \
            -F members_can_create_public_pages=false \
            -F dependabot_alerts_enabled_for_new_repositories=true \
            -F dependabot_security_updates_enabled_for_new_repositories=true \
            -F dependency_graph_enabled_for_new_repositories=true

            # need to have ghas licenses
            # -F advanced_security_enabled_for_new_repositories=true \
            # -F secret_scanning_enabled_for_new_repositories=true \
            # -F secret_scanning_push_protection_enabled_for_new_repositories=true
            
            # create .github and .github-private repos
            # gh api \
            #   --method POST \
            #   -H "Accept: application/vnd.github+json" \
            #   /orgs/${{ steps.issue-parser.outputs.issueparser_org_name }}/repos \
            #   -f name='.github' \
            # -F private=false \
            # -f visibility='public'

            # gh api \
            #   --method POST \
            #   -H "Accept: application/vnd.github+json" \
            #   /orgs/${{ steps.issue-parser.outputs.issueparser_org_name }}/repos \
            #   -f name='.github-private' \
            # -F private=true \
            # -f visibility='private'
            
            # set git config
            echo "setting git config"
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            
            # init and push readme's
            echo "create new directory and clone the repos"
            mkdir github-repos && cd github-repos
            git clone https://github-actions:${{ secrets.ADMIN_TOKEN }}@github.com/${{ steps.issue-parser.outputs.issueparser_org_name }}/.github.git
            git clone https://github-actions:${{ secrets.ADMIN_TOKEN }}@github.com/${{ steps.issue-parser.outputs.issueparser_org_name }}/.github-private.git
            
            echo "copy in base readme's"
            mv ./../src/.github/README.md ./.github/README.md
            mv ./../src/.github-private/README.md ./.github-private/README.md
            
            echo "commit and push the readme's"
            cd ./.github
            git add README.md
            git commit -m "adding readme"
            git push --set-upstream origin main
            
            cd ./../.github-private
            git add README.md
            git commit -m "adding readme"
            git push --set-upstream origin main

      - name: Post successful message
        uses: actions/github-script@v5
        with:
          script: |
            let commentBody
            commentBody = `🚀 New org created successfully

            Visit the following link for the org: [https://github.com/orgs/${{ steps.issue-parser.outputs.issueparser_org_name }}](https://github.com/orgs/${{ steps.issue-parser.outputs.issueparser_org_name }})
            `

            await github.rest.issues.createComment({
              issue_number: ${{ github.event.issue.number }},
              owner: '${{ github.REPOSITORY_OWNER }}',
              repo: '${{ github.event.repository.name }}',
              body: commentBody.replace(/  +/g, '')
            })

      - name: Post failure message
        if: ${{ failure() }}
        uses: actions/github-script@v5
        with:
          script: |
            let commentBody
            commentBody = `😢 The new org could not be created. Please review the [action logs](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for more information.`
            await github.rest.issues.createComment({
              issue_number: ${{ github.event.issue.number }},
              owner: '${{ github.REPOSITORY_OWNER }}',
              repo: '${{ github.event.repository.name }}',
              body: commentBody.replace(/  +/g, '')
            })
